driver:
  name: vagrant
  linked_clones: true
  gui: false
  communicator: winrm
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm
  username: vagrant
  password: vagrant

provisioner:
  name: dsc
  dsc_local_configuration_manager_version: wmf5
  dsc_local_configuration_manager:
    reboot_if_needed: true
  configuration_script_folder: examples
  configuration_script: dsc_configuration.ps1

verifier:
  name: pester
  test_folder: Tests/Integration

platforms:
  - name: windows-2012r2-test
    driver:
      box: trueability/windows-server-2012-r2
      gui: true
      #mwrock/Windows2012R2
    provisioner:
      dsc_local_configuration_manager_version: wmf5
  
suites:
  - name: default